version: '2'
services:
  dbms:
    container_name: esb_rdbms
    build: 
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  manager:
    container_name: esb_manager
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: esb-manager/Dockerfile
    ports:
      - "9443:9443"
  worker1:
    container_name: esb_worker1
    depends_on: 
      - dbms
      - manager
    build:
      context: .
      dockerfile: esb-worker/Dockerfile
    ports:
      - "9444:9443"
