from dockerhub.private.wso2.com/wso2esb:4.9.0

COPY esb_manager/axis2.xml /mnt/wso2/carbon-home/repository/conf/axis2/
COPY esb_manager/carbon.xml /mnt/wso2/carbon-home/repository/conf/
COPY esb_manager/master-datasources.xml /mnt/wso2/carbon-home/repository/conf/datasources/
