from dockerhub.private.wso2.com/wso2esb:4.9.0

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2/carbon-home/repository/components/lib/
COPY esb-manager/axis2.xml /mnt/wso2/carbon-home/repository/conf/axis2/
COPY esb-manager/carbon.xml /mnt/wso2/carbon-home/repository/conf/
COPY esb-manager/master-datasources.xml /mnt/wso2/carbon-home/repository/conf/datasources/
